sudo: required

language: python
python:
  - 2.7

services:
  - docker

install:
  - pip install ansible
  - cd tests
  - sed -i 's/^DOCKER_CONFIG=.*/DOCKER_CONFIG=/' artdcrc
  - sed -i 's/^DOCKER_MACHINE_IP=.*/DOCKER_MACHINE_IP=127.0.0.1/' artdcrc

script:
  - ./artdc.sh init
  - ./artdc.sh provision
  - ./artdc.sh verify
  - ./artdc.sh clean

branches:
  only:
    - master

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
